-- src/implicitfuzz/ingestion/schema.sql
-- provenance/source_location 等复合结构存 JSON TEXT 列，闭包/递归查询留给上层 SQL CTE（不在本计划范围）。

CREATE TABLE IF NOT EXISTS entry_fact (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  schema_version TEXT NOT NULL,
  raw_json TEXT NOT NULL,
  kernel_version TEXT NOT NULL,
  llvm_version TEXT NOT NULL,
  opt_level TEXT NOT NULL,
  bc_unit TEXT NOT NULL,
  function TEXT NOT NULL,
  entry_kind TEXT NOT NULL,
  entry_symbol TEXT NOT NULL,
  associated_syscall TEXT,
  dispatch_table TEXT,
  dispatch_index INTEGER,
  dispatch_role TEXT,
  source_location_json TEXT,
  primary_provenance TEXT NOT NULL,
  provenance_json TEXT NOT NULL,
  confidence TEXT NOT NULL,
  confidence_score REAL
);

CREATE TABLE IF NOT EXISTS call_fact (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  schema_version TEXT NOT NULL,
  raw_json TEXT NOT NULL,
  kernel_version TEXT NOT NULL,
  llvm_version TEXT NOT NULL,
  opt_level TEXT NOT NULL,
  bc_unit TEXT NOT NULL,
  function TEXT NOT NULL,
  caller TEXT NOT NULL,
  callee TEXT NOT NULL,
  call_site TEXT NOT NULL,
  is_indirect INTEGER NOT NULL,
  resolution_method TEXT NOT NULL,
  callee_candidates_json TEXT,
  call_chain_hash TEXT NOT NULL,
  instruction_id TEXT NOT NULL,
  svf_node_id TEXT NOT NULL,
  icfg_node_id TEXT,
  source_location_json TEXT,
  primary_provenance TEXT NOT NULL,
  provenance_json TEXT NOT NULL,
  confidence TEXT NOT NULL,
  confidence_score REAL
);

CREATE TABLE IF NOT EXISTS access_fact (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  schema_version TEXT NOT NULL,
  raw_json TEXT NOT NULL,
  kernel_version TEXT NOT NULL,
  llvm_version TEXT NOT NULL,
  opt_level TEXT NOT NULL,
  bc_unit TEXT NOT NULL,
  function TEXT NOT NULL,
  semantic_op TEXT NOT NULL,
  access_kind TEXT NOT NULL,
  base_object_json TEXT NOT NULL,
  object_scope TEXT NOT NULL,
  access_path_symbolic TEXT,
  numeric_kind TEXT NOT NULL,
  access_path_numeric TEXT,
  field_type TEXT,
  access_path_recovery TEXT NOT NULL,
  instruction_id TEXT NOT NULL,
  svf_node_id TEXT NOT NULL,
  icfg_node_id TEXT,
  cross_opt_key TEXT NOT NULL,
  access_path_json TEXT,
  summary_detail_json TEXT,
  source_location_json TEXT,
  primary_provenance TEXT NOT NULL,
  provenance_json TEXT NOT NULL,
  confidence TEXT NOT NULL,
  confidence_score REAL
);

CREATE TABLE IF NOT EXISTS alias_fact (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  schema_version TEXT NOT NULL,
  raw_json TEXT NOT NULL,
  kernel_version TEXT NOT NULL,
  llvm_version TEXT NOT NULL,
  opt_level TEXT NOT NULL,
  bc_unit TEXT NOT NULL,
  function TEXT NOT NULL,
  object_id_json TEXT NOT NULL,
  points_to_set_json TEXT NOT NULL,
  relation_evidence TEXT NOT NULL,
  pta_kind TEXT NOT NULL,
  source_location_json TEXT,
  primary_provenance TEXT NOT NULL,
  provenance_json TEXT NOT NULL,
  confidence TEXT NOT NULL,
  confidence_score REAL
);

CREATE TABLE IF NOT EXISTS branch_fact (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  schema_version TEXT NOT NULL,
  raw_json TEXT NOT NULL,
  kernel_version TEXT NOT NULL,
  llvm_version TEXT NOT NULL,
  opt_level TEXT NOT NULL,
  bc_unit TEXT NOT NULL,
  function TEXT NOT NULL,
  branch_instruction_id TEXT NOT NULL,
  condition_value TEXT NOT NULL,
  control_deps_json TEXT NOT NULL,
  related_loads_json TEXT NOT NULL,
  slice_range TEXT NOT NULL,
  source_location_json TEXT,
  primary_provenance TEXT NOT NULL,
  provenance_json TEXT NOT NULL,
  confidence TEXT NOT NULL,
  confidence_score REAL
);

CREATE TABLE IF NOT EXISTS gate_seed_fact (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  schema_version TEXT NOT NULL,
  raw_json TEXT NOT NULL,
  kernel_version TEXT NOT NULL,
  llvm_version TEXT NOT NULL,
  opt_level TEXT NOT NULL,
  bc_unit TEXT NOT NULL,
  function TEXT NOT NULL,
  target_symbol TEXT NOT NULL,
  gate_kind TEXT NOT NULL,
  predicate_summary TEXT NOT NULL,
  related_objects_json TEXT NOT NULL,
  related_access_facts_json TEXT NOT NULL,
  source_location_json TEXT,
  primary_provenance TEXT NOT NULL,
  provenance_json TEXT NOT NULL,
  confidence TEXT NOT NULL,
  confidence_score REAL
);

CREATE TABLE IF NOT EXISTS struct_layout_fact (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  schema_version TEXT NOT NULL,
  raw_json TEXT NOT NULL,
  kernel_version TEXT NOT NULL,
  llvm_version TEXT NOT NULL,
  opt_level TEXT NOT NULL,
  bc_unit TEXT NOT NULL,
  function TEXT NOT NULL,
  struct_name TEXT NOT NULL,
  member_name TEXT NOT NULL,
  byte_offset INTEGER NOT NULL,
  member_type TEXT NOT NULL,
  source_location_json TEXT,
  primary_provenance TEXT NOT NULL,
  provenance_json TEXT NOT NULL,
  confidence TEXT NOT NULL,
  confidence_score REAL
);
